---
- name: Install Tomcat
  yum:
    update_cache: yes
    name: tomcat
    state: latest
    
#Copy tomcat server.xml config
- name: Copy tomcat server.xml config
  copy:
    src: files/server.xml
    dest: /etc/tomcat/server.xml
    owner: root
    group: root
    mode: "644"

- name: Creates directory for the new custom page
  file:
    path: /usr/share/tomcat/webapps/ROOT
    owner: root
    group: root
    state: directory

#Copy index.html config
- name: Copy index.html config
  copy:
    src: files/index.html
    dest: /usr/share/tomcat/webapps/ROOT
    owner: root
    group: root
    mode: "644"

- name: Start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
